[platformio]
default_envs = esp32-tx

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
build_type = debug
lib_deps =
	sandeepmistry/LoRa
	bodmer/TJpg_Decoder


[env:esp32-rx]
build_flags =
	-DROLE_RX=1

[env:esp32-tx]
build_flags =
	-DROLE_TX=1
lib_deps = 
		bodmer/TJpg_Decoder
		SD
		sandeepmistry/LoRa

[env:wifi-tx]
build_flags =
	-DROLE_TX=1   
upload_protocol = espota
upload_port = 10.42.0.230
upload_flags =
	--port=3232
	--auth=senha_ota_forte
monitor_speed = 115200
lib_deps =
	ArduinoOTA
	bodmer/TJpg_Decoder
	SD
	sandeepmistry/LoRa
